# Generated by Django 3.0.2 on 2020-01-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Users',
        ),
    ]
