# Generated by Django 3.0.7 on 2020-06-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200131_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
