# Generated by Django 3.0.7 on 2020-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dark_theme', models.BooleanField(default=False)),
                ('session_time', models.PositiveIntegerField(default=300)),
            ],
        ),
    ]
