# Generated by Django 3.0.7 on 2020-06-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
